grc: Open the source of a hierachical block sometimes produces error messages
1. Open a fg that contains a hierachical block
2. Select the hierachical block
3. Open the source of the selected hierachical block from the grc menu

gives the following error in the terminal

Loading: "/home/schroer/gnuradiocomponents/gr-noaa/examples/doppler_test.grc"
>>> Done

Loading: "/home/schroer/gnuradiocomponents/gr-funcube/examples/decodeapt.grc"
>>> Done
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc/gui/Application.py", line 782, in _handle_action
    for b in flow_graph.selected_blocks():
  File "/usr/local/gnuradio/lib64/python3.11/site-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 673, in <genexpr>
    return (e for e in self.selected_elements if e.is_block)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Set changed size during iteration

I'm not sure why set is changed but according to the python recommendations changing to
self.selected_elements.copy() fixes this issue.

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>