fft_filter: Create unique_ptr with gr::make_unique
The boost::make_unique was added in boost 1.56.0 while the minimal boost
version in CMakeLists.txt is set to 1.53. And the std::make_unique is a
c++14 feature so it still can't be used.

This fixes a compile error on CentOS 7 where the boost version is 1.53

/cache/workdir/Centos_7_6_0/build_Centos_7_6/src/gr-filter/lib/fft_filter.cc:17:43:
 fatal error: boost/smart_ptr/make_unique.hpp: No such file or directory
 #include <boost/smart_ptr/make_unique.hpp>