gr-qtgui: freq_sink and others produce wrong error messages, when GUI Hint is used
freq_sink_x, sink_x, vector_sink_f .... produce error messages like
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/blocks/_templates.py", line 77, in render
    return template.render(**namespace)
  File "/usr/lib/python3.10/site-packages/mako/template.py", line 473, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3.10/site-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f00a04d3a00", line 115, in render_body
TypeError: unsupported operand type(s) for %: 'NoneType' and 'str'

if the showport entry is changed, but widget will be properly placed.
To avoid this error message the order of Show Msg Port and GUI Hint must be changed.

And I changed the entry for Show Msg Port from a text entry to a pull down menu.

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>