fft: Add message to static_assert
In c++11 the static_assert takes two parameters while in c++17 a version
with only one parameter was added

https://en.cppreference.com/w/cpp/language/static_assert

Compilation on CentOS 7 with gcc 4.8.5 fails with

gr-fft/lib/fft.cc:164:62: error: expected ',' before ')' token
     static_assert(sizeof(fftwf_complex) == sizeof(gr_complex));