variable_header_default correctly check access_code
int(eval(access_code)) fails with 
ValueError: invalid literal for int() with base 10
if access_code does not simply consists of digits.
The main purpose of this check is to use digital.packet_utils.default_access_code as access_code  if access_code  == 0
which is the default setting.
This patch uses digital.packet_utils.default_access_code as default but sets the access code to $access_code if this code consits of digits.