purge boost/math/special_functions/erf.hpp
`boost/math/special_functions/erf.hpp` causes compile errors. Also, it
is only used for two functions `erf` and `erfc`. Both functions are
available in `cmath`. Including this boost header back in 2012 might
have fixed an issue, but now it causes huge trouble. A 1500+ line
compile error with:

    /usr/include/boost/math/special_functions/detail/erf_inv.hpp:355:50: error: invalid suffix Q on floating constant
        boost::math::erfc_inv(static_cast<T>(BOOST_MATH_BIG_CONSTANT(T, 64, 1e-900)), Policy());