grc-qt: AttributeError: 'GUIPort' object has no attribute 'is_sink'
This error is a bit tricky to reproduce.

Generate a simple flowgraph

signal source( float ) -> audio sink (float, single input)
Save the fg and restart grc.
Modify the audio sink to 2 inputs and try connect the source port
to the new sink input port.

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>
(cherry picked from commit f6cf83affbf2c29a27fa6befaa2fc1b448ef1db8)
Signed-off-by: Jeff Long <willcode4@gmail.com>