uhd: Declare float to time_spec_t implicitly convertible
Without this declaration, function calls that require a time_spec_t
argument must be provided with such an argument, even if there is
a default argument.

For example, in the RFNoC DDC block, we couldn't call set_freq() as
such:

```python
ddc_block.set_freq(0.0, 0)
```

It would produce the following error:
```
TypeError: set_freq(): incompatible function arguments. The following
    argument types are supported:
1. (self: gnuradio.uhd.uhd_python.rfnoc_ddc,
    freq: float,
    chan: int,
    time: gnuradio.uhd.uhd_python.time_spec_t = 0.0) -> float
```

Even though the argument `time` is optional, the default value of 0.0 is
not able to satisfy the requirements. By adding the
`py::implicitly_convertible` call, we declare float convertible to time
spec, and the call above can proceed.

Signed-off-by: Martin Braun <martin.braun@ettus.com>