grc: Improve check for connection in properties dialog
Without this fix, GRC tries to populate a full block-property dialog
when opening a property dialog on connections. This improves the
checking for the right attributes to correctly identify connections, and
removes the following spurious output when opening property dialogs on
connections:

Traceback (most recent call last):
  File "..../grc/gui/PropsDialog.py", line 210, in update_gui
    self._update_docs_page()
  File "..../grc/gui/PropsDialog.py", line 219, in _update_docs_page
    in_tree = self._block.category and self._block.category[0] == "Core"
AttributeError: 'Connection' object has no attribute 'category'

Signed-off-by: Martin Braun <martin.braun@ettus.com>
(cherry picked from commit 0ecdc338c33287157277c2f5d460857fa7bb5f74)
Signed-off-by: Jeff Long <willcode4@gmail.com>