grc: follow up to #7455
Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/Test/./callhier.py", line 24, in get_state_directory
    log.warn(f"Found persistent state path '{newpath}', but file does not exist. " +
    ^^^
NameError: name 'log' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/schroer/gnuradiocomponents/Test/./callhier.py", line 47, in <module>
    sys.path.append(os.environ.get('GRC_HIER_PATH', get_state_directory()))
                                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/schroer/gnuradiocomponents/Test/./callhier.py", line 33, in get_state_directory
    log.warn("Could not retrieve GNU Radio persistent state directory from GNU Radio." +
    ^^^
NameError: name 'log' is not defined

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>