ctrlport: change to doc; no -p flag required for gr-ctrlport-monitor
Updating documentation to reflect that -p flag isn't necessary. It causes this error for me:

ValueError: invalid literal for int() with base 10: '-p'