grc: add yaml_config block fails
grc --gtk only shows an error but displays the block

Loading: "/home/schroer/gnuradiocomponents/bugs/yaml_config.grc"
Failed to evaluate variable block yaml_config_0
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/core/FlowGraph.py", line 286, in _reload_variables
    value = eval(variable_block.value, namespace,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

grc --qt shows an error and segfaults sometimes

Failed to evaluate variable block yaml_config_0
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/core/FlowGraph.py", line 286, in _reload_variables
    value = eval(variable_block.value, namespace,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: ''
Traceback (most recent call last):
  File "/usr/local/gnuradio/lib64/python3.12/site-packages/gnuradio/grc/gui_qt/components/block_library.py", line 140, in <lambda>
    lambda block: self.add_block(block.data(Qt.UserRole))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>
(cherry picked from commit 2a8b58ca18b5bbd978ca6cd495450c2a9b4ea2b8)
Signed-off-by: Jeff Long <willcode4@gmail.com>