gr-fec: correcting function name in GRC xml
I think that these lines were causing this error: AttributeError: 'ldpc_H_matrix_sptr' object has no attribute 'get_base_ptr'

so changing from get_base_ptr to get_base_sptr