dev-4.0: grc fails to use alsa_sink block
Trying to load an ALSA_SINK in grc fails with

Traceback (most recent call last):
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/gui/MainWindow.py", line 156, in _add_block_to_current_flow_graph
    self.current_flow_graph.add_new_block(key)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/gui/canvas/flowgraph.py", line 165, in add_new_block
    block = self.new_block(key)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/FlowGraph.py", line 328, in new_block
    block = self.parent_platform.make_block(self, block_id, **kwargs)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/platform.py", line 432, in make_block
    return cls(parent, **kwargs)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/gui/canvas/block.py", line 30, in __init__
    super(self.__class__, self).__init__(parent, **n)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/blocks/block.py", line 71, in __init__
    self.sinks = [port_factory(parent=self, **params)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/blocks/block.py", line 71, in <listcomp>
    self.sinks = [port_factory(parent=self, **params)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/platform.py", line 440, in make_port
    return cls(parent, **kwargs)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/gui/canvas/port.py", line 30, in __init__
    super(self.__class__, self).__init__(parent, direction, **n)
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/ports/port.py", line 64, in __init__
    self.multiplicity = multiplicity
  File "/usr/local/gnuradio/lib64/python3.10/site-packages/gnuradio/grc/core/utils/descriptors/evaluated.py", line 62, in __set__
    attribs[self.name] = type(self.default)(value)
ValueError: invalid literal for int() with base 10: 'int'

This is due to e68a3c83d246e02ad6ed163cffa33c663ca3fe92.
grc_type now returns always raw for refs that do not start with typekeys.
This patch returns the correct value for parameters.

Signed-off-by: Volker Schroer <3470424+dl1ksv@users.noreply.github.com>